### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by john20xdoe** [john20xdoe/experimental-typescript-html#1]
- [ ] create Layout module
- [ ] create common `reference.d.ts` or sort of Main
- [ ] use a theme (dashboard bootstrap) that cane be replaced with another theme
- [ ] publish
